### ISSUE TITLE
Unexplained intermittent outages

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-api#101]
> 2020-02-20T17:41:24.695619+00:00 app[web.1]: QueryFailedError: syntax error at or near ")"
> 2020-02-20T17:41:24.695620+00:00 app[web.1]:     at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
> 2020-02-20T17:41:24.695621+00:00 app[web.1]:     at Query.callback (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
> 2020-02-20T17:41:24.695621+00:00 app[web.1]:     at Query.handleError (/app/node_modules/pg/lib/query.js:142:17)
> 2020-02-20T17:41:24.695622+00:00 app[web.1]:     at Connection.connectedErrorMessageHandler (/app/node_modules/pg/lib/client.js:211:17)
> 2020-02-20T17:41:24.695622+00:00 app[web.1]:     at Connection.emit (events.js:198:13)
> 2020-02-20T17:41:24.695623+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:126:12)
> 2020-02-20T17:41:24.695623+00:00 app[web.1]:     at Socket.emit (events.js:198:13)
> 2020-02-20T17:41:24.695623+00:00 app[web.1]:     at addChunk (_stream_readable.js:288:12)
> 2020-02-20T17:41:24.695624+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:269:11)
> 2020-02-20T17:41:24.695668+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:224:10)
> 2020-02-20T17:41:24.705389+00:00 app[web.1]: [31m[Nest] 23   - [39m02/20/2020, 5:41:24 PM   [38;5;3m[ExceptionsHandler] [39m[31msyntax error at or near ")"[39m[38;5;3m +10ms[39m

**Comment by allthesignals** [comment]
This could be related, from Digital Ocean:

> CPU Utilization Percent is currently at 100.00%, above setting of 70.00% for the last 5m
> View droplet: https://cloud.digitalocean.com/droplets/97498754?i=266877
> IP: 162.243.44.171
> Edit monitor: https://cloud.digitalocean.com/monitors/86028d92-6e01-428f-8915-965323e6685b?i=266877

**Comment by allthesignals** [comment]
<img width="1116" alt="Screen Shot 2020-02-21 at 10 51 01 AM" src="https://user-images.githubusercontent.com/5004319/75049408-20c89580-5498-11ea-95d6-4e130821bd32.png">

**Comment by allthesignals** [comment]
Some users are running into this snag:

![image](https://user-images.githubusercontent.com/5004319/75049444-30e07500-5498-11ea-901f-510800ff58cc.png)

**Comment by allthesignals** [comment]
This may be related to the CPU running hot on the DO droplet.

We discovered we can't move to managed postgres because the function ST_AsMVT depends on a low-level library (libprotobuf-c) which isn't installed on the managed postgres servers.

**Comment by allthesignals** [comment]
Asking for all completed projects is expensive on the service, might be slowing things down

**Comment by allthesignals** [comment]
dcp_certifiedreferred[]=1262304001
dcp_certifiedreferred[]=1609459199
dcp_publicstatus[]=Completed
dcp_publicstatus[]=Filed
dcp_publicstatus[]=In Public Review
dcp_publicstatus[]=Prefiled
dcp_publicstatus[]=Unknown
page=1

**Comment by allthesignals** [comment]
<img width="1192" alt="Screen Shot 2020-02-24 at 4 01 39 PM" src="https://user-images.githubusercontent.com/5004319/75192393-220cf300-5722-11ea-9361-be5bdcb8d6d9.png">

The tiles query seems to be the most time consuming... note that it will request 4 tiles for every view.
